import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeadBar } from "@/components/Main/HeadBar";
import Footer from "@/components/Main/Footer";
import { Providers } from "./Providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased  mx-auto  justify-center w-full`}>
        <Providers>
          <div className="mx-auto  justify-center w-full md:w-5/6 lg:w-5/6 xl:w-5/6">
          <HeadBar />
          {children}
          <Toaster position="top-center" />
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
